# Generated by Django 5.0.1 on 2024-02-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('Price', models.FloatField()),
                ('pdetails', models.CharField(max_length=50, verbose_name='Product Details')),
                ('cat', models.CharField(choices=[('mobile', 1), ('Shoes', 2), ('Cloths', 3)], max_length=50, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
